### 영화 목록 조회
GET http://localhost:3000/movies

### 사람 목록 조회
GET http://localhost:3000/people

### 영화 즐겨찾기 저장
POST http://localhost:3000/favorites
content-type: application/json

{
  "name": "A New Hope",
  "type": "movie",
  "url": "https://swapi.dev/api/films/1/"
}

### 영화 즐겨찾기 목록 조회
GET http://localhost:3000/favorites